"""rename column in subscribe

Revision ID: a9efc853d0f9
Revises: e84ecc7b6736
Create Date: 2026-05-03 08:23:24.179162

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9efc853d0f9"
down_revision: Union[str, Sequence[str], None] = "e84ecc7b6736"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscription",
        "post_limit",
        new_column_name="active_post_limit",
        schema="content",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscription",
        "active_post_limit",
        new_column_name="post_limit",
        schema="content",
        nullable=False,
    )
    # ### end Alembic commands ###
