"""Init Database

Revision ID: e84ecc7b6736
Revises:
Create Date: 2026-05-02 17:31:38.176553

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e84ecc7b6736"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("str_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("icon_name", sa.String(length=255), nullable=False),
        sa.Column("icon_seeded", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("str_id"),
        schema="content",
    )
    op.create_table(
        "subscription",
        sa.Column("str_id", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("post_limit", sa.Integer(), nullable=False),
        sa.Column("post_lifetime_hours", sa.Integer(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint("duration_days > 0", name="subscription_check_duration_days_positive"),
        sa.CheckConstraint("post_limit > 0", name="subscription_check_post_limit_positive"),
        sa.CheckConstraint("price >= 0", name="subscription_check_price_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("str_id"),
        schema="content",
    )
    op.create_table(
        "user",
        sa.Column("tg_id", sa.Integer(), nullable=False),
        sa.Column("first_activity", sa.DateTime(), nullable=False),
        sa.Column("last_activity", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tg_id"),
        schema="content",
    )
    op.create_table(
        "post",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("image_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("price", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            "geo",
            geoalchemy2.types.Geometry(
                geometry_type="POINT", srid=4326, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
            ),
            nullable=False,
        ),
        sa.Column("pub_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("disable_at", sa.DateTime(), nullable=False),
        sa.Column("delete_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "ARCHIVE", "VALIDATE", name="poststatus", schema="content"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint("price >= 0", name="post_check_price_positive"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["content.product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["content.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="content",
    )
    op.create_index("idx_post_geo_gist", "post", ["geo"], unique=False, schema="content", postgresql_using="gist")
    op.create_table(
        "user_subscription",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("purchase_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["content.subscription.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["content.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="content",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_subscription", schema="content")
    op.drop_index("idx_post_geo_gist", table_name="post", schema="content", postgresql_using="gist")
    op.drop_table("post", schema="content")
    op.drop_table("user", schema="content")
    op.drop_table("subscription", schema="content")
    op.drop_table("product", schema="content")
    # ### end Alembic commands ###
