"""create indexes

Revision ID: 5a83491be32b
Revises: a9efc853d0f9
Create Date: 2026-05-08 17:20:38.627203

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5a83491be32b"
down_revision: Union[str, Sequence[str], None] = "a9efc853d0f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_post_disable_at_active", "post", ["disable_at"], unique=False, schema="content", postgresql_where=sa.text("status = 'ACTIVE'")
    )
    op.create_index("idx_post_product_status", "post", ["product_id", "status"], unique=False, schema="content")
    op.create_index("idx_post_user_status", "post", ["user_id", "status"], unique=False, schema="content")
    op.create_index(
        "idx_user_sub_active_uid", "user_subscription", ["user_id"], unique=False, schema="content", postgresql_where=sa.text("is_active = true")
    )
    op.create_index(
        "idx_user_sub_expires_active",
        "user_subscription",
        ["expires_at"],
        unique=False,
        schema="content",
        postgresql_where=sa.text("is_active = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_sub_expires_active", table_name="user_subscription", schema="content", postgresql_where=sa.text("is_active = true"))
    op.drop_index("idx_user_sub_active_uid", table_name="user_subscription", schema="content", postgresql_where=sa.text("is_active = true"))
    op.drop_index("idx_post_user_status", table_name="post", schema="content")
    op.drop_index("idx_post_product_status", table_name="post", schema="content")
    op.drop_index("idx_post_disable_at_active", table_name="post", schema="content", postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###
