[pytest]
pythonpath= .
env = 
    DATABASE_URL=mock_value
    RABBITMQ_URL=mock_value
    S3_ENDPOINT_URL=mock_value
    S3_ACCESS_KEY=admin
    S3_SECRET_KEY=password
    S3_BUCKET_NAME=test-bucket
    DATABASE_SCHEMA=public